apiVersion: v2
name: external-secrets
description: Wrapper chart for External Secrets Operator
version: 1.0.0
dependencies:
  - name: external-secrets
    version: 0.9.13
    repository: https://charts.external-secrets.io