apiVersion: v2
name: ingress-nginx
description: Wrapper chart for Nginx Ingress Controller
version: 1.0.0
dependencies:
  - name: ingress-nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx